# Generated by Django 4.2.3 on 2023-07-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('curr_floor', models.IntegerField()),
                ('direction', models.CharField(max_length=255)),
                ('is_door_open', models.BooleanField()),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('direction', models.CharField(max_length=255)),
                ('elevator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liftapp.elevator')),
            ],
        ),
        migrations.AddField(
            model_name='elevator',
            name='request_id',
            field=models.ManyToManyField(to='liftapp.request'),
        ),
    ]
